# 数据库配置信息
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/datascreen?useUnicode=true&useSSL=false&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&useLegacyDatetimeCode=false&serverTimezone=Hongkong&nullCatalogMeansCurrent=true
    username: root
    password: 123456
    # 返回json数据时间格式化全局
#  jackson:
#    date-format: yyyy-MM-dd
#    time-zone: Asia/Shanghai

server:
  port: 8081
